accueil:
  path: /
  controller: App\Controller\AccueilController::index

a_propos:
  path: /a_propos
  controller: App\Controller\A_proposController::index

connexion:
  path: /connexion
  controller: App\Controller\SecurityController::login

inscription:
  path: /inscription
  controller: App\Controller\InscriptionController::index
