accueil:
  path: /
  controller: App\Controller\AccueilController::index

publier_trajet:
  path: /publier_trajet
  controller: App\Controller\AnnonceController::createAnnonce

connexion:
  path: /connexion
  controller: App\Controller\SecurityController::login

inscription:
  path: /inscription
  controller: App\Controller\RegistrationController::register

profil:
  path: /profil
  controller: App\Controller\ProfileController::index

deconnexion:
  path: /deconnexion

annonce_show:
  path: /annonce/{id}
  controller: App\Controller\ShowAnnonceController::index

annonces:
  path: /annonces
  controller: App\Controller\AnnonceListController::index
